services:
  scraper:
    build: .
    container_name: bricks
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: bricks_postgres
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

volumes:
  postgres_data: